---
- hosts: localhost
  connection: local
  vars_files:
    - /home/anil/ansible-youtube/assignment/secrets.yml

  tasks:
   - name: start an instance with a public IP address
     amazon.aws.ec2_instance:
       name: "{{ item.name }}"
       instance_type: t2.micro
       security_group: default
       key_name: "ubuntu"
       region: ap-south-1
       aws_access_key: "{{ ec2_aws_access_key }}"  # From vault as defined
       aws_secret_key: "{{ ec2_aws_secret_key }}"  # From vault as defined      
       network:
        assign_public_ip: true
       image_id: "{{ item.image }}"
       wait: yes
     loop:
       - { image: "ami-00bb6a80f01f03502" , name: "managed-node-1" }
     register: ec2_instance

   -  name: "Wait for EC2 instance to be running"
      wait_for:
        host: "{{ ec2.instances[0].public_dns_name }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
        when: ec2.instances is defined and ec2.instances | length > 0

   -  name: Add EC2 instance to inventory
      add_host:
        name: "{{ ec2.instances[0].public_dns_name }}"
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ubuntu.pem

   