---
- hosts: all
  become: true

  tasks:
  # - name: Print all the ansible gathered ansible facts
  #   ansible.builtin.debug:
  #    var: ansible_facts
   - name: shutdown ubuntu instance only
     ansible.builtin.command: /sbin/shutdown -t now
     when:
       ansible_facts['os_family'] == "Debian" , "RedHat"