---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    instance_type: "{{ type }}"
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_aws_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_aws_secret_key}}"  # From vault as defined      
    network:
      assign_public_ip: true
    image_id: ami-00bb6a80f01f03502
  register: ec2_instance
